[CmdletBinding()]
param(
  [switch]$Check
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$tokensRoot = Join-Path $repoRoot 'tokens'
$outputPath = Join-Path $tokensRoot 'build\neoglass.css'

function ConvertTo-Map($value) {
  if ($value -is [System.Management.Automation.PSCustomObject]) {
    $map = [ordered]@{}
    foreach ($property in $value.PSObject.Properties) { $map[$property.Name] = ConvertTo-Map $property.Value }
    return $map
  }
  if ($value -is [System.Collections.IEnumerable] -and $value -isnot [string]) {
    return @($value | ForEach-Object { ConvertTo-Map $_ })
  }
  return $value
}

function Merge-Map([System.Collections.IDictionary]$target, [System.Collections.IDictionary]$source) {
  foreach ($key in $source.Keys) {
    if ($target.Contains($key) -and $target[$key] -is [System.Collections.IDictionary] -and $source[$key] -is [System.Collections.IDictionary]) {
      Merge-Map $target[$key] $source[$key]
    } else {
      $target[$key] = $source[$key]
    }
  }
}

$source = [ordered]@{}
foreach ($directory in @('primitive', 'semantic', 'component', 'profiles', 'themes')) {
  Get-ChildItem -LiteralPath (Join-Path $tokensRoot $directory) -File -Filter '*.json' | Sort-Object FullName | ForEach-Object {
    $document = ConvertTo-Map (Get-Content -Raw -Encoding UTF8 -LiteralPath $_.FullName | ConvertFrom-Json)
    Merge-Map $source $document
  }
}

$tokenTable = @{}
function Collect-Tokens([System.Collections.IDictionary]$node, [string[]]$path, [string]$inheritedType) {
  $tokenType = if ($node.Contains('$type')) { [string]$node['$type'] } else { $inheritedType }
  if ($node.Contains('$value')) {
    $tokenTable[$path -join '.'] = @{ Type = $tokenType; Value = $node['$value'] }
  }
  foreach ($key in $node.Keys | Where-Object { -not $_.StartsWith('$') }) {
    if ($node[$key] -is [System.Collections.IDictionary]) {
      Collect-Tokens $node[$key] ($path + [string]$key) $tokenType
    }
  }
}
Collect-Tokens $source @() $null

function Resolve-Value($value, [System.Collections.Generic.HashSet[string]]$trail) {
  if ($value -is [string] -and $value -match '^\{(.+)\}$') {
    $reference = $Matches[1]
    if (-not $tokenTable.ContainsKey($reference)) { throw "Unknown token reference: {$reference}" }
    if (-not $trail.Add($reference)) { throw "Circular token reference: $reference" }
    $resolved = Resolve-Value $tokenTable[$reference].Value $trail
    [void]$trail.Remove($reference)
    return $resolved
  }
  return $value
}

function Convert-CssValue([string]$tokenType, $value) {
  $resolved = Resolve-Value $value ([System.Collections.Generic.HashSet[string]]::new())
  if ($resolved -is [System.Collections.IDictionary] -and $resolved.Contains('colorSpace') -and $resolved['colorSpace'] -eq 'srgb') {
    $rgb = @($resolved['components'] | ForEach-Object { [math]::Round(([double]$_) * 255) }) -join ' '
    if ($resolved.Contains('alpha')) { return "rgb($rgb / $($resolved['alpha']))" }
    return "rgb($rgb)"
  }
  if ($resolved -is [System.Collections.IDictionary] -and $resolved.Contains('value') -and $resolved.Contains('unit')) {
    return "$($resolved['value'])$($resolved['unit'])"
  }
  if ($tokenType -eq 'cubicBezier' -and $resolved -is [System.Collections.IEnumerable] -and $resolved -isnot [string]) {
    return "cubic-bezier($(@($resolved) -join ', '))"
  }
  return [string]$resolved
}

function Css-Name([string]$path) { return '--ng-' + ($path -replace '\.', '-') }
function Declarations([string]$prefix) {
  $lines = [System.Collections.Generic.List[string]]::new()
  foreach ($path in $tokenTable.Keys | Sort-Object) {
    if ($prefix) {
      if (-not $path.StartsWith($prefix)) { continue }
      $outputPath = $path.Substring($prefix.Length)
    } elseif ($path.StartsWith('theme.')) {
      continue
    } else {
      $outputPath = $path
    }
    $entry = $tokenTable[$path]
    $lines.Add("  $(Css-Name $outputPath): $(Convert-CssValue $entry.Type $entry.Value);")
  }
  return $lines
}

$css = [System.Collections.Generic.List[string]]::new()
$css.Add('/* Generated by scripts/Build-Tokens.ps1. Do not edit directly. */')
$css.Add('/* Experimental output for NeoGlass X. */')
$css.Add('')
$css.Add(':root, [data-theme="dark"] {')
$css.AddRange([string[]](Declarations ''))
$css.Add('}')
foreach ($theme in @('dark', 'high-contrast')) {
  $prefix = "theme.$theme."
  $css.Add('')
  $css.Add("[data-theme=`"$theme`"] {")
  $css.AddRange([string[]](Declarations $prefix))
  if ($theme -eq 'high-contrast') { $css.Add('  --ng-material-backdrop-blur: 0px;') }
  $css.Add('}')
}
$css.Add('')
$css.Add('[data-motion="none"] { --ng-motion-duration-fast: 0ms; --ng-motion-duration-standard: 0ms; }')
$css.Add('[data-transparency="none"] { --ng-material-backdrop-blur: 0px; }')
$css.Add('@media (prefers-reduced-motion: reduce) { :root { --ng-motion-duration-fast: 0ms; --ng-motion-duration-standard: 0ms; } }')
$content = ($css -join [Environment]::NewLine) + [Environment]::NewLine

if ($Check) {
  if (-not (Test-Path -LiteralPath $outputPath) -or [System.IO.File]::ReadAllText($outputPath, [System.Text.Encoding]::UTF8) -ne $content) {
    Write-Output 'Token build output is stale. Run scripts/Build-Tokens.ps1.'
    exit 1
  }
  Write-Output 'Token build output is current.'
  exit 0
}

[System.IO.File]::WriteAllText($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $outputPath"
