[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $repoRoot 'MANIFEST.md'
$files = Get-ChildItem -LiteralPath $repoRoot -Recurse -File | Where-Object {
  $_.FullName -ne $manifestPath -and $_.FullName -notmatch '\\.git\\'
} | Sort-Object FullName

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Repository Manifest')
$lines.Add('')
$lines.Add('- Generated by `scripts/Update-Manifest.ps1`.')
$lines.Add('- This snapshot is release evidence, not a required hand-maintained source file.')
$lines.Add('- Version: 0.2.0-alpha.1')
$lines.Add("- File count excluding this manifest: $($files.Count)")
$lines.Add('')
$lines.Add('| Path | Size | SHA-256 |')
$lines.Add('|---|---:|---|')
foreach ($file in $files) {
  $relative = $file.FullName.Substring($repoRoot.Length + 1).Replace([System.IO.Path]::DirectorySeparatorChar, '/')
  $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
  $lines.Add(("| ``{0}`` | {1} | ``{2}`` |" -f $relative, $file.Length, $hash))
}

[System.IO.File]::WriteAllLines($manifestPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "Updated $manifestPath with $($files.Count) files."
